### ISSUE TITLE
There are no configuration file for health checking of platform arm and x86_64

### ISSUE THREAD

**Issue by BIRooter** [kernelci/lava-docker#171]
Configuration files in /etc/lava-server/dispatcher-config/health-checks/ don't match all supported machine types. 

I found a health check definition of x86 in following website:
https://validation.linaro.org/scheduler/job/3996185/definition

However,  I couldn't find that definition for arm.

could you update corresponding code to support both of them?

**Comment by montjoie** [comment]
x86 is not a valid device type, it does not bind to a specific device.
For ARM, the standard for device type name is the devicetree name.

But since most x86 is "compatible", the job you linked could be used for any x86 device.
But for arm there is no universal job, each ARM device need its own device tree so its own job definition.

**Comment by BIRooter** [comment]
Thanks for your response!

I will look for device(s) using ssh to deploy kernel image.
