### ISSUE TITLE
Adding devices to lava

### ISSUE THREAD

**Issue by manojtiwary22** [kernelci/lava-docker#58]
I'm little confused about adding devices to lava . As described i've edited boards.yaml to add raspberrypi3 board. But when I'm loading docker images I'm getting following error:
local_master1_1 is up-to-date
Recreating local_lab-slave-0_1 ... error

ERROR: for local_lab-slave-0_1  Cannot start service lab-slave-0: linux runtime spec devices: error gathering device information while adding custom device "/dev/bcm2837-rpi-3-b-01": lstat /dev/bcm2837-rpi-3-b-01: no such file or directory

ERROR: for lab-slave-0  Cannot start service lab-slave-0: linux runtime spec devices: error gathering device information while adding custom device "/dev/bcm2837-rpi-3-b-01": lstat /dev/bcm2837-rpi-3-b-01: no such file or directory
ERROR: Encountered errors while bringing up the project.
Help me resolve the issue. I've attached boards.yaml file contents below

[boardfile.txt](https://github.com/kernelci/lava-docker/files/2528412/boardfile.txt)

**Comment by mungaip** [comment]
Hello manojtiwary22,
I also encountered this issue a little while ago. It is because the handle /dev/bcm2837-rpi-3-b-01 doesn't exist on the host machine. 
I solved this issue by creating a symbolic link to the actual device handle. For example if the handle for the rasberry pi 3 is /dev/ttyUSB0, run "sudo ln -s /dev/ttyUSB0 /dev/bcm2837-rpi-3-b-01".

**Comment by khilman** [comment]
If the link doesn't exist on the host machine, then the udev rules created by lava-docker have not been properly installed.

After running the lavalab-gen.py script, in the "output/<host>" directory, you'll find a "deploy.sh" script which will install/update the udev rules, as well as do the docker-compose build/up.

@montjoie please update the quickstart in the README to use the deploy.sh script instead of directly doing the docker-compose commands.

**Comment by manojtiwary22** [comment]
thank u patrykmungai and khilman my issue got resolved.
