### ISSUE TITLE
Is NFS supported in the slave docker image?

### ISSUE THREAD

**Issue by mungaip** [kernelci/lava-docker#73]
I am trying to run a test job using NFS- https://lava.ciplatform.org/scheduler/job/59 . The file system isn't mounting though.
Having a look in the docker container:
1. It doesn't seem that the NFS daemon is running
```
root@lab-cip-renesas:/# service nfs-kernel-server status
nfsd not running
```
2. /var/lib/lava/dispatcher/tmp does not support NFS export
```
root@lab-cip-renesas:/# service nfs-kernel-server start
mount: permission denied
Exporting directories for NFS kernel daemon...exportfs: /var/lib/lava/dispatcher/tmp
 failed!
```
Has NFS support been added to the slave docker image?

**Comment by khilman** [comment]
It has not been added yet because there are complications with running nfs-kernel-server inside the container.

The workaround is to run nfs-kernel-server on the docker host and use bind mounts into the container so LAVA can unpack the rootfs images in the right place.

We have a goal to add this to lava-docker eventually, but it's not currently a priority.  Patches welcome if you get it working.  :)

**Comment by khilman** [comment]
Support for NFS is now merged.

**Comment by patersonc** [comment]
Thanks Kevin.
